# Generated by Django 5.0.3 on 2024-03-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('exam', 'Exam'), ('summary', 'Summary'), ('course', 'Course'), ('other', 'Other')], max_length=10)),
                ('content', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('speciality', models.CharField(choices=[('informatique', 'Licence en Informatique de Gestion'), ('science_gestion', 'Licence en Science de gestion'), ('economie', 'Licence en economie'), ('master_pro', 'Master Professionnels'), ('master_recherche', 'Matster de recherche')], max_length=60)),
                ('subject_name', models.CharField(choices=[], max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
