# Generated by Django 5.0.3 on 2024-03-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedocumentsapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='speciality',
            field=models.CharField(choices=[('informatique', 'Informatique De Gestion'), ('science_gestion', 'Science De Gestion'), ('economie', 'Economie'), ('master_pro', 'Master Professionnels'), ('master_recherche', 'Master De Recherche')], max_length=60),
        ),
        migrations.AlterField(
            model_name='document',
            name='subject_name',
            field=models.CharField(max_length=200),
        ),
    ]
