# Generated by Django 5.0.3 on 2024-03-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedocumentsapi', '0002_alter_document_speciality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
