# Generated by Django 5.0.3 on 2024-03-28 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedocumentsapi', '0003_alter_document_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocumentsViewed', models.PositiveIntegerField()),
                ('DocumentsDownloaded', models.PositiveIntegerField()),
                ('DocumentsAdded', models.PositiveIntegerField()),
            ],
        ),
    ]
