# Generated by Django 5.0.3 on 2024-03-28 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedocumentsapi', '0005_studypoints_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studypoints',
            name='DocumentsAdded',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studypoints',
            name='DocumentsDownloaded',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studypoints',
            name='DocumentsViewed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
