# Generated by Django 5.0.3 on 2024-03-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedocumentsapi', '0006_alter_studypoints_documentsadded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studypoints',
            name='last_viewed_document_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
