# Generated by Django 5.0.3 on 2024-03-30 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managedocumentsapi', '0008_vieweddocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studypoints',
            name='last_viewed_document_id',
        ),
    ]
