# Generated by Django 5.0.3 on 2024-04-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedocumentsapi', '0012_document_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studypoints',
            name='Timespent',
            field=models.BigIntegerField(default=0),
        ),
    ]
