# Generated by Django 5.0.3 on 2024-04-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedocumentsapi', '0014_remove_studypoints_timespent_usertimespent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertimespent',
            name='TimeSpent',
            field=models.FloatField(default=0.0),
        ),
    ]
