# Generated by Django 5.0.3 on 2024-04-23 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedocumentsapi', '0015_alter_usertimespent_timespent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertimespent',
            name='document_id',
        ),
        migrations.AddField(
            model_name='usertimespent',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='managedocumentsapi.document'),
        ),
    ]
