# Generated by Django 5.0.3 on 2024-04-24 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedocumentsapi', '0016_remove_usertimespent_document_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertimespent',
            name='document',
        ),
        migrations.AddField(
            model_name='usertimespent',
            name='document_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserTimeSpent3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeSpent', models.FloatField(default=0.0)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='managedocumentsapi.document')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
