# Generated by Django 5.0.3 on 2024-03-23 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapi', '0002_remove_feedback_contactnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='contactNumber',
            field=models.CharField(blank=True, null=True),
        ),
    ]
