# Generated by Django 5.0.3 on 2024-03-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapi', '0003_feedback_contactnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='contactNumber',
            field=models.CharField(blank=True, default=None),
        ),
    ]
