# Generated by Django 5.0.3 on 2024-03-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('companyName', models.TextField()),
                ('location', models.TextField()),
                ('contactInformation', models.TextField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('description', models.TextField()),
                ('skillsGained', models.TextField()),
                ('report', models.FileField(upload_to='internshipexperiences/')),
            ],
        ),
    ]
