# Generated by Django 5.0.3 on 2024-04-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimanageinternships', '0002_internshipexperience_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipexperience',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
