# Generated by Django 5.0.3 on 2024-04-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindmattersapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gratitudetext', models.CharField()),
            ],
        ),
    ]
