# Generated by Django 5.0.3 on 2024-04-18 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mindmattersapi', '0002_wall'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wall',
        ),
    ]
